# Model 1: Logistic Regression Model

## DATA PRE-PROCESSING

## 1. Importiing the libraries

In [144]:
import numpy as np   #library for mathematical operations in python
import matplotlib.pyplot as plt   #Its a plotting library used for 2D graphics
import pandas as pd  #Library to import datasets and manage them

## 2. Importing Dataset

In [145]:
dataset = pd.read_excel("C:/Users/NIKITA/Desktop/Nucleus/Nucleus.xlsx")

In [146]:
dataset

ID  Checking_amount  Term  Credit_score  Gender  Marital_status   \
0     101              988    15           796       1                0   
1     102              458    15           813       1                0   
2     103              158    14           756       1                0   
3     104              300    25           737       1                0   
4     105               63    24           662       1                0   
5     106             1071    20           828       0                1   
6     107             -192    13           856       0                0   
7     108              172    16           763       1                0   
8     109              585    20           778       1                0   
9     110              189    19           649       0                1   
10    111              214    19           742       0                1   
11    112              710    18           772       1                0   
12    113              268    18           815       0                1   
13    114              262    21           726       1                0   
14    115               24    21           705       1                0   
15    116              887    18           779       1                0   
16    117              360    20           710       0                1   
17    118              571    16           779       0                1   
18    119              382    15           757       0                1   
19    120             1151    13           784       0                0   
20    121              167    19           773       0                1   
21    122              491    25           747       0                1   
22    123              156    20           851       0                1   
23    124              285    18           700       0                1   
24    125              -38    25           710       1                0   
25    126              794    21           861       1                0   
26    127              347    19           799       1                0   
27    128              258    18           766       1                0   
28    129              490    15           798       0                1   
29    130               16    22           764       0                0   
..    ...              ...   ...           ...     ...              ...   
970  1173              -94    21           964       0                1   
971  1174               43    20           680       0                1   
972  1175              548    16           782       0                1   
973  1176              282    15           582       0                1   
974  1177              471    16           820       0                1   
975  1178              510    22           782       0                1   
976  1179              185    16           782       0                1   
977  1180              -98    23           612       0                1   
978  1181              372    16           748       0                1   
979  1182              188    15           841       0                1   
980  1184               39    15           719       0                1   
981  1185              855    20           684       0                1   
982  1186              475    14           745       0                1   
983  1187              189    15           608       0                1   
984  1188             -431    19           861       0                1   
985  1189              452    18           824       0                1   
986  1190              180    17           843       0                1   
987  1191              172    26           729       1                0   
988  1192             -665    18           740       0                1   
989  1193              405    12           825       0                1   
990  1194              631    15           679       0                1   
991  1195              742    15

## 3. To Determine Dependent & Independent variables

In [147]:
X = dataset.iloc[:, :-1].values 
y = dataset.iloc[:, 16].values 

In [148]:
X

array([[ 101,  988,   15, ...,   12,   38,    1],
       [ 102,  458,   15, ...,   25,   36,    1],
       [ 103,  158,   14, ...,   43,   34,    1],
       ...,
       [1201,  343,   16, ...,   99,   31,    4],
       [1202,  709,   16, ...,  113,   28,    6],
       [1203,  991,   15, ...,   95,   33,    8]], dtype=int64)

In [149]:
y

array([0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,

## 4. Treating missing values in dataset

In [150]:
from sklearn.preprocessing import Imputer   
imputer_1 = Imputer(missing_values = 'NaN', strategy = 'mean', axis=0)
imputer_1 = imputer_1.fit(X[:, 1:3])
X[:, 1:3] = imputer_1.transform(X[:, 1:3])

C:\Users\NIKITA\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


## 5. Splitting the Dataset into training set & test set

In [153]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 0)

## 6. Feature Scaling

In [154]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [155]:
X_train

array([[ 0.67616189, -0.67616189,  0.55036429, ...,  1.57452105,
         0.20454124,  1.48541263],
       [-1.47893576,  1.47893576, -0.03808487, ...,  0.9881941 ,
        -0.2831875 , -0.33624824],
       [-1.47893576,  1.47893576, -0.5670631 , ..., -0.26441346,
        -0.2831875 , -0.94346853],
       ...,
       [-1.47893576,  1.47893576,  0.36569142, ..., -1.09060143,
         0.44840561,  1.48541263],
       [ 0.67616189, -0.67616189,  0.14658801, ..., -0.23776224,
         0.93613436,  0.27097205],
       [ 0.67616189, -0.67616189,  0.54097415, ...,  0.96154288,
         0.20454124,  0.87819234]])

In [156]:
X_test

array([[ 0.67616189, -0.67616189,  1.81803403, ..., -0.55757694,
        -1.50250936,  0.87819234],
       [-1.47893576,  1.47893576,  1.3923474 , ..., -0.50427449,
         0.93613436, -0.33624824],
       [-1.47893576,  1.47893576, -0.67348476, ..., -1.22385756,
        -1.74637374, -0.94346853],
       ...,
       [-1.47893576,  1.47893576, -0.93640885, ...,  0.6683794 ,
        -0.03932313, -0.33624824],
       [ 0.67616189, -0.67616189,  0.44394264, ..., -0.82408919,
         0.20454124,  0.87819234],
       [-1.47893576,  1.47893576, -1.13986202, ...,  1.28135758,
         0.44840561,  1.48541263]])

## Fitting Logistic Regression to the Training Data

In [157]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

C:\Users\NIKITA\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=0, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

## Predicting the test set results

In [158]:
y_pred = classifier.predict(X_test)

In [159]:
y_pred

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0], dtype=int64)

## Making confusion matrix- Logistic Regression

In [160]:
from sklearn.metrics import confusion_matrix
confu_m = confusion_matrix(y_test,y_pred)

In [161]:
confu_m

array([[155,   5],
       [  8,  32]], dtype=int64)

# Model 2: SUPPORT VECTOR MACHINE

In [163]:
from sklearn.svm import SVC
classifier_svm = SVC(kernel='linear',random_state=0)
classifier_svm.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=0,
  shrinking=True, tol=0.001, verbose=False)

## Predicting the test set results

In [165]:
y_pred = classifier_svm.predict(X_test)
y_pred

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0], dtype=int64)

## Making confusion matrix - Support Vector Machine

In [167]:
from sklearn.metrics import confusion_matrix
confu_mm = confusion_matrix(y_test,y_pred)
confu_mm

array([[157,   3],
       [  7,  33]], dtype=int64)

## Model 2: DECISION TREE